% Options for packages loaded elsewhere
% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\PassOptionsToPackage{dvipsnames,svgnames,x11names}{xcolor}
%
\documentclass[
  letterpaper,
]{report}
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{amsmath,amssymb}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
% Make \paragraph and \subparagraph free-standing
\makeatletter
\ifx\paragraph\undefined\else
  \let\oldparagraph\paragraph
  \renewcommand{\paragraph}{
    \@ifstar
      \xxxParagraphStar
      \xxxParagraphNoStar
  }
  \newcommand{\xxxParagraphStar}[1]{\oldparagraph*{#1}\mbox{}}
  \newcommand{\xxxParagraphNoStar}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
  \let\oldsubparagraph\subparagraph
  \renewcommand{\subparagraph}{
    \@ifstar
      \xxxSubParagraphStar
      \xxxSubParagraphNoStar
  }
  \newcommand{\xxxSubParagraphStar}[1]{\oldsubparagraph*{#1}\mbox{}}
  \newcommand{\xxxSubParagraphNoStar}[1]{\oldsubparagraph{#1}\mbox{}}
\fi
\makeatother


\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother





\setlength{\emergencystretch}{3em} % prevent overfull lines

\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}



 


\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}
\makeatletter
\@ifpackageloaded{tcolorbox}{}{\usepackage[skins,breakable]{tcolorbox}}
\@ifpackageloaded{fontawesome5}{}{\usepackage{fontawesome5}}
\definecolor{quarto-callout-color}{HTML}{909090}
\definecolor{quarto-callout-note-color}{HTML}{0758E5}
\definecolor{quarto-callout-important-color}{HTML}{CC1914}
\definecolor{quarto-callout-warning-color}{HTML}{EB9113}
\definecolor{quarto-callout-tip-color}{HTML}{00A047}
\definecolor{quarto-callout-caution-color}{HTML}{FC5300}
\definecolor{quarto-callout-color-frame}{HTML}{acacac}
\definecolor{quarto-callout-note-color-frame}{HTML}{4582ec}
\definecolor{quarto-callout-important-color-frame}{HTML}{d9534f}
\definecolor{quarto-callout-warning-color-frame}{HTML}{f0ad4e}
\definecolor{quarto-callout-tip-color-frame}{HTML}{02b875}
\definecolor{quarto-callout-caution-color-frame}{HTML}{fd7e14}
\makeatother
\makeatletter
\@ifpackageloaded{bookmark}{}{\usepackage{bookmark}}
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\AtBeginDocument{%
\ifdefined\contentsname
  \renewcommand*\contentsname{Table of contents}
\else
  \newcommand\contentsname{Table of contents}
\fi
\ifdefined\listfigurename
  \renewcommand*\listfigurename{List of Figures}
\else
  \newcommand\listfigurename{List of Figures}
\fi
\ifdefined\listtablename
  \renewcommand*\listtablename{List of Tables}
\else
  \newcommand\listtablename{List of Tables}
\fi
\ifdefined\figurename
  \renewcommand*\figurename{Figure}
\else
  \newcommand\figurename{Figure}
\fi
\ifdefined\tablename
  \renewcommand*\tablename{Table}
\else
  \newcommand\tablename{Table}
\fi
}
\@ifpackageloaded{float}{}{\usepackage{float}}
\floatstyle{ruled}
\@ifundefined{c@chapter}{\newfloat{codelisting}{h}{lop}}{\newfloat{codelisting}{h}{lop}[chapter]}
\floatname{codelisting}{Listing}
\newcommand*\listoflistings{\listof{codelisting}{List of Listings}}
\makeatother
\makeatletter
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\@ifpackageloaded{subcaption}{}{\usepackage{subcaption}}
\makeatother
\makeatletter
\@ifpackageloaded{sidenotes}{}{\usepackage{sidenotes}}
\@ifpackageloaded{marginnote}{}{\usepackage{marginnote}}
\makeatother
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Property Development Opportunity Analysis},
  pdfauthor={HDAdvisors},
  colorlinks=true,
  linkcolor={blue},
  filecolor={Maroon},
  citecolor={Blue},
  urlcolor={Blue},
  pdfcreator={LaTeX via pandoc}}


\title{Property Development Opportunity Analysis}
\usepackage{etoolbox}
\makeatletter
\providecommand{\subtitle}[1]{% add subtitle to \maketitle
  \apptocmd{\@title}{\par {\large #1 \par}}{}{}
}
\makeatother
\subtitle{A Comprehensive Assessment of Underutilized Assets}
\author{HDAdvisors}
\date{2025-12-16}
\begin{document}
\maketitle

\renewcommand*\contentsname{Table of contents}
{
\hypersetup{linkcolor=}
\setcounter{tocdepth}{2}
\tableofcontents
}

\bookmarksetup{startatroot}

\chapter{Property Development Opportunity
Analysis}\label{property-development-opportunity-analysis}

\section{Report Purpose}\label{report-purpose}

This analysis provides:

\begin{itemize}
\tightlist
\item
  \textbf{Strategic Insights}: Identification of high-potential
  development opportunities
\item
  \textbf{Data-Driven Decisions}: Evidence-based property assessments
\item
  \textbf{Geographic Analysis}: Regional distribution and market
  potential
\end{itemize}

\section{How to Use This Report}\label{how-to-use-this-report}

\begin{itemize}
\tightlist
\item
  \textbf{Executive Summary}: Quick overview and key findings
\item
  \textbf{Methodology}: Understanding our analytical approach
\item
  \textbf{Analysis Results}: Detailed findings and insights
\item
  \textbf{Summary Statistics}: Portfolio-wide metrics
\item
  \textbf{Property Profiles}: Individual property assessments
\item
  \textbf{Appendices}: Technical details and references
\end{itemize}

\begin{tcolorbox}[enhanced jigsaw, bottomtitle=1mm, title=\textcolor{quarto-callout-tip-color}{\faLightbulb}\hspace{0.5em}{Interactive Features}, colbacktitle=quarto-callout-tip-color!10!white, titlerule=0mm, left=2mm, colframe=quarto-callout-tip-color-frame, rightrule=.15mm, toptitle=1mm, breakable, leftrule=.75mm, arc=.35mm, coltitle=black, bottomrule=.15mm, toprule=.15mm, opacitybacktitle=0.6, opacityback=0, colback=white]

This report includes interactive visualizations and tools. Use the
filters and controls to explore the data dynamically.

\end{tcolorbox}

\section{Navigation}\label{navigation}

Use the table of contents on the left to navigate between sections, or
use the search function to find specific topics.

\bookmarksetup{startatroot}

\chapter*{Executive Summary}\label{executive-summary}
\addcontentsline{toc}{chapter}{Executive Summary}

\markboth{Executive Summary}{Executive Summary}

This analysis examines properties in the Episcopal Diocese of Virginia
with fewer than 30 Sunday attendees, focusing on development potential
through five key metrics: land value, zoning/density, acreage,
environmental limitations, and Qualified Census Tract (QCT) status. This
report was done for VEREP (Virginia Episcopal Real Estate Partners) in
conjunction with case study projects HDAdvisors is facilitating.

\section*{At a Glance: Top 10
Properties}\label{at-a-glance-top-10-properties}
\addcontentsline{toc}{section}{At a Glance: Top 10 Properties}

\markright{At a Glance: Top 10 Properties}

\begin{longtable}[t]{>{\centering\arraybackslash}p{3em}llr>{}r}

\caption{\label{tbl-top-dev}Top Development Opportunities}

\tabularnewline

\toprule
Rank & Address & City & Acres & Tier\\
\midrule
\textbf{1} & 10520 MAIN ST, FAIRFAX 22030 & FAIRFAX & 4.11 & \cellcolor{YlOrRd}{\textcolor{green}{High}}\\
\textbf{2} & 1 TRURO LN, FAIRFAX 22030 & FAIRFAX & 3.44 & \cellcolor{YlOrRd}{\textcolor{green}{High}}\\
\textbf{3} & 10490 MAIN ST, FAIRFAX 22030 & FAIRFAX & 0.61 & \cellcolor{YlOrRd}{\textcolor{green}{Moderate}}\\
\textbf{4} & 3241 BRUSH DR, FALLS CHURCH 22042 & FALLS CHURCH & 5.64 & \cellcolor{YlOrRd}{\textcolor{green}{High}}\\
\textbf{5} & 11253 WEST RIVER RD, AYLETT 23009 & AYLETT & 0.58 & \cellcolor{YlOrRd}{\textcolor{green}{Moderate}}\\
\addlinespace
\textbf{6} & 37018 GLENDALE ST, PURCELLVILLE 20132 & PURCELLVILLE & 2.02 & \cellcolor{YlOrRd}{\textcolor{green}{High}}\\
\textbf{7} & 1484 HOCKETT RD, MANAKIN SABOT 23103 & MANAKIN SABOT & 9.49 & \cellcolor{YlOrRd}{\textcolor{green}{High}}\\
\textbf{8} & 1704 WEST LABURNUM AVE, RICHMOND 23227 & RICHMOND & 1.47 & \cellcolor{YlOrRd}{\textcolor{green}{Moderate}}\\
\textbf{9} & 39518 LITTLE RIVER TPKE, ALDIE 20105 & ALDIE & 1.13 & \cellcolor{YlOrRd}{\textcolor{green}{Moderate}}\\
\textbf{10} & 5092 GRACE CHURCH LN, MIDLAND 22728 & MIDLAND & 8.34 & \cellcolor{YlOrRd}{\textcolor{green}{High}}\\
\bottomrule

\end{longtable}

\begin{figure}[H]

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{executive-summary_files/figure-pdf/fig-tier-distribution-1.pdf}}

}

\caption{\label{fig-tier-distribution}Distribution of Properties by
Development Potential}

\end{figure}%

\section*{Key Findings}\label{key-findings}
\addcontentsline{toc}{section}{Key Findings}

\markright{Key Findings}

\subsection*{Portfolio Summary}\label{portfolio-summary}
\addcontentsline{toc}{subsection}{Portfolio Summary}

\begin{figure}

\begin{minipage}{0.25\linewidth}

\begin{tcolorbox}[enhanced jigsaw, breakable, leftrule=.75mm, left=2mm, arc=.35mm, toprule=.15mm, bottomrule=.15mm, colframe=quarto-callout-note-color-frame, rightrule=.15mm, opacityback=0, colback=white]

\vspace{-3mm}\textbf{100}\vspace{3mm}

Parcels Analyzed

\end{tcolorbox}

\end{minipage}%
%
\begin{minipage}{0.25\linewidth}

\begin{tcolorbox}[enhanced jigsaw, breakable, leftrule=.75mm, left=2mm, arc=.35mm, toprule=.15mm, bottomrule=.15mm, colframe=quarto-callout-tip-color-frame, rightrule=.15mm, opacityback=0, colback=white]

\vspace{-3mm}\textbf{18}\vspace{3mm}

Strong Potential (High)

\end{tcolorbox}

\end{minipage}%
%
\begin{minipage}{0.25\linewidth}

\begin{tcolorbox}[enhanced jigsaw, breakable, leftrule=.75mm, left=2mm, arc=.35mm, toprule=.15mm, bottomrule=.15mm, colframe=quarto-callout-warning-color-frame, rightrule=.15mm, opacityback=0, colback=white]

\vspace{-3mm}\textbf{36.8}\vspace{3mm}

Top Developable Acres

\end{tcolorbox}

\end{minipage}%
%
\begin{minipage}{0.25\linewidth}

\begin{tcolorbox}[enhanced jigsaw, breakable, leftrule=.75mm, left=2mm, arc=.35mm, toprule=.15mm, bottomrule=.15mm, colframe=quarto-callout-important-color-frame, rightrule=.15mm, opacityback=0, colback=white]

\vspace{-3mm}\textbf{248}\vspace{3mm}

Total Portfolio Acres

\end{tcolorbox}

\end{minipage}%

\end{figure}%

\subsection*{Significant Underutilized
Assets}\label{significant-underutilized-assets}
\addcontentsline{toc}{subsection}{Significant Underutilized Assets}

\begin{figure}

\begin{minipage}{0.33\linewidth}

\begin{tcolorbox}[enhanced jigsaw, breakable, leftrule=.75mm, left=2mm, arc=.35mm, toprule=.15mm, bottomrule=.15mm, colframe=quarto-callout-warning-color-frame, rightrule=.15mm, opacityback=0, colback=white]

\vspace{-3mm}\textbf{3 Parcels (3.9 acres)}\vspace{3mm}

Surface Parking Lots

\end{tcolorbox}

\end{minipage}%
%
\begin{minipage}{0.33\linewidth}

\begin{tcolorbox}[enhanced jigsaw, breakable, leftrule=.75mm, left=2mm, arc=.35mm, toprule=.15mm, bottomrule=.15mm, colframe=quarto-callout-warning-color-frame, rightrule=.15mm, opacityback=0, colback=white]

\vspace{-3mm}\textbf{22 Parcels (98.6 acres)}\vspace{3mm}

Vacant/Open Space

\end{tcolorbox}

\end{minipage}%
%
\begin{minipage}{0.33\linewidth}

\begin{tcolorbox}[enhanced jigsaw, breakable, leftrule=.75mm, left=2mm, arc=.35mm, toprule=.15mm, bottomrule=.15mm, colframe=quarto-callout-tip-color-frame, rightrule=.15mm, opacityback=0, colback=white]

\vspace{-3mm}\textbf{56 Parcels (81.6 acres)}\vspace{3mm}

Financial Need Congregations

\end{tcolorbox}

\end{minipage}%

\end{figure}%

This defines ``need'' as:

\begin{itemize}
\tightlist
\item
  Sites with active congregations (has\_congregation equals TRUE)
\item
  Declining congregations
\item
  Declining giving
\end{itemize}

\subsection*{Geographic Distribution}\label{geographic-distribution}
\addcontentsline{toc}{subsection}{Geographic Distribution}

\begin{figure}[H]

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{executive-summary_files/figure-pdf/fig-geographic-dists-1.pdf}}

}

\caption{\label{fig-geographic-dists}Properties by County}

\end{figure}%

Development opportunities are distributed across Virginia, with
concentrations in:

\begin{itemize}
\tightlist
\item
  Urban/suburban areas with strong walkability scores
\item
  Markets with favorable demographics and LIHTC eligibility
\item
  Transit-accessible locations supporting reduced parking requirements
\end{itemize}

\subsection*{Congregation Vitality
Summary}\label{congregation-vitality-summary}
\addcontentsline{toc}{subsection}{Congregation Vitality Summary}

\subsection*{Congregation Vitality
Summary}\label{congregation-vitality-summary-1}
\addcontentsline{toc}{subsection}{Congregation Vitality Summary}

\begin{longtable*}[t]{lr}
\toprule
\cellcolor[HTML]{445ca9}{\textcolor{white}{\textbf{Metric}}} & \cellcolor[HTML]{445ca9}{\textcolor{white}{\textbf{Value}}}\\
\midrule
\textbf{Congregations with <30 Sunday Attendance} & \textbf{37}\\
Total Parcels Analyzed & 104\\
Average Parcels per Congregation & 2.8\\
Average Sunday Attendance & 17 people\\
Average Annual Pledge & \$44,271\\
\addlinespace
\textbf{Congregations in Financial Need} & \textbf{21}\\
\bottomrule
\end{longtable*}

\begin{verbatim}
:::

## Next Steps

1.  **Priority Assessment**: Review top-ranked properties for immediate action
2.  **Feasibility Studies**: Conduct detailed feasibility analysis for top candidates
3.  **Stakeholder Engagement**: Engage relevant stakeholders for high-priority sites
4.  **Financial Planning**: Develop funding strategies and timelines


::: {.quarto-book-part}


`<!-- quarto-file-metadata: eyJyZXNvdXJjZURpciI6Ii4ifQ== -->`{=html}

```{=html}
<!-- quarto-file-metadata: eyJyZXNvdXJjZURpciI6Ii4iLCJib29rSXRlbVR5cGUiOiJwYXJ0IiwiYm9va0l0ZW1OdW1iZXIiOm51bGwsImJvb2tJdGVtRGVwdGgiOjB9 -->
\end{verbatim}

\bookmarksetup{startatroot}

\chapter*{Methodology \& Data}\label{methodology-data}
\addcontentsline{toc}{chapter}{Methodology \& Data}

\markboth{Methodology \& Data}{Methodology \& Data}

:::

\chapter{Background \& Data Sources}\label{background-data-sources}

\section{VEREP Parcel Dataset}\label{verep-parcel-dataset}

This analysis utilizes the Virginia Episcopal Real Estate Portfolio
(VEREP) parcel dataset, compiled by CGS Consultants. The dataset
(originally 790 parcels) was further filtered to look at
parcels/properties with small congregations and includes:

\begin{itemize}
\item
  \textbf{104 parcels} across Virginia
\item
  Comprehensive property characteristics (size, use, zoning)
\item
  Environmental constraints (floodplains, wetlands, easements)
\item
  Location metrics (walkability, transit access)
\item
  Market indicators (median income, demographics)
\end{itemize}

\section{Congregation Statistics
(2014-2023)}\label{congregation-statistics-2014-2023}

Financial and membership data provides context on congregation health:

\begin{itemize}
\tightlist
\item
  Sunday attendance trends
\item
  Membership changes
\item
  Plate \& pledge revenue
\item
  10-year trend analysis
\end{itemize}

\begin{tcolorbox}[enhanced jigsaw, bottomtitle=1mm, title=\textcolor{quarto-callout-note-color}{\faInfo}\hspace{0.5em}{Data Quality Note}, colbacktitle=quarto-callout-note-color!10!white, titlerule=0mm, left=2mm, colframe=quarto-callout-note-color-frame, rightrule=.15mm, toptitle=1mm, breakable, leftrule=.75mm, arc=.35mm, coltitle=black, bottomrule=.15mm, toprule=.15mm, opacitybacktitle=0.6, opacityback=0, colback=white]

Not all properties have associated congregation data. Properties without
congregation information received neutral scores in the financial need
category.

\end{tcolorbox}

\section{Data Quality Issues}\label{data-quality-issues}

Of the 104 properties analyzed with fewer than 30 Sunday attendees, 101
(97.1\%) have incomplete data --- meaning they are missing at least one
of the six key development metrics (land value, acreage, wetland
coverage, flood zone, QCT status, or zoning). This high rate reflects
broader data quality challenges identified in CGS's initial VEREP study.

While environmental constraint data (wetlands, flood zones) accounts for
much of the missing information, 15 properties (14.4\%) are missing land
value entirely, limiting our ability to assess their financial
potential. The breakdown below classifies these data gaps to help
prioritize follow-up research. Once complete, these properties can be
more precisely evaluated for development opportunities.

\begin{longtable*}[l]{>{\raggedright\arraybackslash}p{25em}>{\raggedleft\arraybackslash}p{12em}}
\toprule
Metric & Value\\
\midrule
\textbf{Total properties analyzed (<30 attendance)} & 104\\
\textbf{Properties with incomplete data (score < 6/6)} & 30 (28.8\%)\\
\textbf{Properties missing land value} & 15 (14.4\%)\\
\textbf{VEREP properties not matched to congregation} & 162 (of 790 total VEREP properties)\\
\bottomrule
\end{longtable*}

\pandocbounded{\includegraphics[keepaspectratio]{methodology-overview_files/figure-pdf/missing-data-chart-1.pdf}}

\chapter{Data Source Details}\label{data-source-details}

Of the 104 properties in the analysis subset, 101 (97\%) were initially
flagged as having incomplete data based on six key fields: land value,
acreage, wetland percentage, flood zone, qualified census tract (QCT)
status, and zoning designation.

Upon closer examination, wetland data accounted for the vast majority of
missing values (93.3\% of properties). This gap reflects limitations in
the source wetland layer coverage rather than an absence of wetland
features. For properties without wetland data, we applied a default
value of 0\%, operating under the assumption that parcels not captured
in the National Wetlands Inventory contain no significant wetland
features. Similarly, the 5 properties (4.8\%) missing FEMA flood zone
designations were assigned zone ``X,'' indicating minimal flood hazard,
consistent with areas outside mapped floodplains.

Acreage and QCT status were complete across all 104 properties. Land
value and zoning data remained incomplete for 15 properties each
(14.4\%). These fields were retained as missing rather than imputed, as
accurate values require verification through county assessor records and
local zoning ordinances. Properties lacking these values are flagged for
manual follow-up.

Following these adjustments, the number of properties with incomplete
data decreased from 101 to approximately 25, representing those still
requiring land value or zoning verification.

\chapter{Analytical Framework}\label{analytical-framework}

\section{Development Potential
Scoring}\label{development-potential-scoring}

Our methodology evaluates six key dimensions:

\pandocbounded{\includegraphics[keepaspectratio]{analytical-framework_files/figure-pdf/scoring-visual-1.pdf}}

\textbf{Constraint Penalties:} Properties receive deductions for flood
zones (-40), significant wetlands (-35), easements (-30), and historic
district designation (-25).

\textbf{Development Tiers}

Properties are classified into five tiers based on composite scores:

\begin{itemize}
\tightlist
\item
  \textbf{Tier 1 (75-100):} High Priority - Immediate development
  candidates
\item
  \textbf{Tier 2 (60-74):} Strong Potential - Near-term opportunities
\item
  \textbf{Tier 3 (45-59):} Moderate Potential - Requires creative
  solutions
\item
  \textbf{Tier 4 (30-44):} Limited Potential - Significant barriers
  exist
\item
  \textbf{Tier 5 (\textless30):} Not Recommended - Unsuitable for
  development
\end{itemize}

\chapter{Understanding the Development
Criteria}\label{understanding-the-development-criteria}

\section{Why These Factors Matter}\label{why-these-factors-matter}

The development potential score is calculated using seven key criteria,
each weighted according to its importance in determining development
viability. Our scoring methodology reflects decades of real estate
development experience and incorporates both market realities and
mission-aligned priorities. Each criterion was selected to balance
financial viability with community impact, ensuring that recommended
properties can support sustainable development while serving
congregational needs.

\subsection{Property Size: The Goldilocks
Principle}\label{property-size-the-goldilocks-principle}

\textbf{Weight: 20\%}

\marginnote{\begin{footnotesize}

\textbf{Optimal Range}: 0.5-5 acres

Properties that are ``just right'' for development.

\end{footnotesize}}

Not too small to be economically viable, not too large to be financially
unwieldy.

\begin{figure}[H]

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{development-criteria_files/figure-pdf/fig-size-scoring-1.pdf}}

}

\caption{\label{fig-size-scoring}Property Size Scoring Curve}

\end{figure}%

\begin{figure}[H]

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{development-criteria_files/figure-pdf/fig-size-distribution-1.pdf}}

}

\caption{\label{fig-size-distribution}Distribution of Property Sizes in
Portfolio}

\end{figure}%

\textbf{Why This Matters}:

\begin{itemize}
\tightlist
\item
  \textbf{Too small (\textless0.5 acres)}: Limited development options,
  high per-unit costs
\item
  \textbf{Optimal (0.5-5 acres)}: Maximum flexibility and economic
  efficiency
\item
  \textbf{Too large (\textgreater10 acres)}: Requires significant
  capital, complex phasing
\end{itemize}

Property size significantly influences development feasibility, but
bigger isn't always better. Properties under a quarter-acre typically
lack the critical mass needed for financially viable
development---construction costs per unit rise sharply, and parking or
open space requirements become impossible to meet. Conversely, parcels
exceeding 10 acres often present unique challenges: they may require
complex phasing, demand substantial upfront capital, or face community
resistance to density.

\subsection{Current Use: Identifying Low-Hanging
Fruit}\label{current-use-identifying-low-hanging-fruit}

\textbf{Weight: 25\%}

\marginnote{\begin{footnotesize}

\textbf{Optimal Use}: Vacant or nearly vacant with access to
infrastructure

\end{footnotesize}}

Properties with minimal current utilization represent immediate
opportunities.

\begin{longtable}[t]{l>{}cl}

\caption{\label{tbl-use-scoring}Current Use Scoring Matrix}

\tabularnewline

\toprule
Current Use & Score & Rationale\\
\midrule
Parking Lot & \cellcolor{RdYlGn}{\textcolor{black}{\textbf{95}}} & Immediate development potential, minimal displacement\\
Open Space & \cellcolor{RdYlGn}{\textcolor{black}{\textbf{90}}} & Low-value use, easy conversion\\
Mixed/Other & \cellcolor{RdYlGn}{\textcolor{black}{\textbf{60}}} & Varies by specific circumstances\\
Residence & \cellcolor{RdYlGn}{\textcolor{black}{\textbf{40}}} & Displacement considerations\\
School & \cellcolor{RdYlGn}{\textcolor{black}{\textbf{35}}} & Active community use\\
\addlinespace
Church (primary) & \cellcolor{RdYlGn}{\textcolor{black}{\textbf{30}}} & Core mission function\\
Cemetery & \cellcolor{RdYlGn}{\textcolor{black}{\textbf{5}}} & Restricted use, not developable\\
\bottomrule

\end{longtable}

\begin{figure}[H]

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{development-criteria_files/figure-pdf/fig-use-distribution-1.pdf}}

}

\caption{\label{fig-use-distribution}Properties by Current Use Type}

\end{figure}%

\textbf{Highest Potential: Parking Lots and Open Space}

Not all church property serves its highest and best use. Surface parking
lots represent prime redevelopment opportunities---they're already
cleared and graded, typically have minimal environmental constraints,
and often sit underutilized six days per week. A parking lot that serves
200 congregants on Sunday morning but stands empty Monday through
Saturday represents an enormous opportunity cost.

Open space scores similarly high, particularly when it's amenity-free
lawn rather than programmed recreation or memorial gardens. These
properties can be reimagined while potentially retaining some green
space within new development.

\subsection{Location Quality: Following the
Market}\label{location-quality-following-the-market}

\textbf{Weight: 20\%}

\begin{figure}[H]

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{development-criteria_files/figure-pdf/fig-location-factors-1.pdf}}

}

\caption{\label{fig-location-factors}Location Quality Components}

\end{figure}%

\begin{figure}[H]

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{development-criteria_files/figure-pdf/fig-walkability-dist-1.pdf}}

}

\caption{\label{fig-walkability-dist}Distribution of Walkability Scores}

\end{figure}%

\textbf{Key Metrics: Walkability Score and Transit Access}

Real estate development fundamentally responds to location. A walkable,
transit-rich site commands higher rents, attracts more diverse tenants,
and often qualifies for density bonuses or reduced parking
requirements---all factors that improve project economics.

Walkability scores measure proximity to everyday needs: grocery stores,
schools, employment centers, healthcare. High walkability (15-20 on our
scale) indicates a property can support car-light or car-free
households, expanding the potential tenant base to include young
professionals, seniors aging in place, and lower-income families for
whom car ownership is cost-prohibitive.

Transit access amplifies these benefits. Properties within a
quarter-mile of frequent bus service or half-mile of rail stations can
often negotiate reduced parking requirements with municipalities---a
significant cost savings when structured parking runs \$25,000-\$40,000
per space to construct.

\subsection{Financial Need: Aligning Development with
Mission}\label{financial-need-aligning-development-with-mission}

\textbf{Weight: 15\%}

\begin{figure}[H]

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{development-criteria_files/figure-pdf/fig-financial-need-1.pdf}}

}

\caption{\label{fig-financial-need}Properties by Financial Need Level}

\end{figure}%

\textbf{Priority: Congregations with Declining Resources}

This criterion explicitly centers mission over pure market return.
Congregations experiencing sustained pledge declines often face a
difficult reality: their historic buildings demand expensive
maintenance, but shrinking budgets make upkeep increasingly burdensome.
Many such congregations sit on valuable real estate that could, through
thoughtful development, generate steady income streams while maintaining
their worship and ministry.

A ground lease arrangement, for example, might provide a struggling
congregation with \$50,000-\$150,000 annually in stable income---enough
to fund a part-time rector, maintain the building, and sustain core
ministries. This approach transforms real estate from a drain on
resources into a mission enabler.

Properties associated with growing congregations score lower not because
they lack development potential, but because the urgency is less acute.
These communities likely have more options and less immediate financial
pressure.

\subsection{Market Potential: Reading Economic
Signals}\label{market-potential-reading-economic-signals}

\textbf{Weight: 10\%}

\begin{table}

\caption{\label{tbl-market-indicators}Market Potential Scoring Criteria}

\centering{

\begin{longtabu} to \linewidth {>{\raggedright}X>{\centering}X>{\raggedright}X>{\raggedright}X}
\toprule
Indicator & Weight & High Score & Data Source\\
\midrule
QCT Status & 40\% & In Qualified Census Tract & HUD QCT Maps\\
Area Median Income & 30\% & >\$75,000 AMI & ACS 5-Year\\
Population Growth & 15\% & >2\% annual growth & Census\\
Housing Demand & 15\% & High demand market & Local market data\\
\bottomrule
\end{longtabu}

}

\end{table}%

\textbf{Indicator: Area Median Income and LIHTC Eligibility}

Development must respond to market demand. Properties in higher-income
areas (median incomes above \$75,000) typically support market-rate
housing, ground-floor retail, or mixed-use projects that can
cross-subsidize affordable components. These projects attract
conventional financing and a broader range of development partners.

Properties in Qualified Census Tracts (QCTs) gain additional scoring
weight because they unlock Low-Income Housing Tax Credit (LIHTC)
financing---the nation's primary mechanism for affordable housing
production. LIHTC projects in QCTs receive point advantages in
competitive funding rounds, improving their feasibility. For
mission-driven institutions committed to affordable housing, QCT
properties offer a rare alignment of social impact and financial
viability.

\subsection{Zoning: Navigating Regulatory
Reality}\label{zoning-navigating-regulatory-reality}

\textbf{Weight: 10\%}

\begin{table}

\caption{\label{tbl-zoning-scoring}Zoning Category Scoring}

\centering{

\begin{longtabu} to \linewidth {>{\raggedright}X>{}c>{\raggedright}X}
\toprule
Zoning Category & Score & Development Impact\\
\midrule
Mixed Use & \textbf{90} & Maximum flexibility for housing + retail\\
Multi-Family Residential & \textbf{85} & Aligned with housing mission\\
Commercial & \textbf{70} & May require use variance for residential\\
Single-Family Residential & \textbf{50} & Density limitations, rezoning often needed\\
Agricultural & \textbf{40} & Significant restrictions, rural areas\\
\addlinespace
Conservation & \textbf{10} & Severe limitations, unlikely candidate\\
\bottomrule
\end{longtabu}

}

\end{table}%

\textbf{Favorable: Mixed-Use, Commercial, and Residential Districts}

Zoning powerfully shapes what's buildable and how quickly projects move
from concept to construction. Properties zoned for residential or
mixed-use development typically offer by-right development
opportunities---projects that don't require lengthy rezoning processes,
conditional use permits, or special exceptions.

Conversely, properties in restrictive single-family or conservation
districts may require multi-year regulatory processes, neighborhood
opposition, and uncertain outcomes. While such projects occasionally
succeed, they demand patient capital and sophisticated development
partners.

\subsection{Environmental and Regulatory Constraints: Deal-Breakers
vs.~Speed-Bumps}\label{environmental-and-regulatory-constraints-deal-breakers-vs.-speed-bumps}

\textbf{Weight: 5\% (applied as penalties)}

\begin{table}

\caption{\label{tbl-constraints}Constraint Penalties Applied to
Development Score}

\centering{

\begin{longtabu} to \linewidth {>{\raggedright}X>{}c>{\centering}X>{\raggedright}X}
\toprule
Constraint & Score Penalty & Mitigation Difficulty & Notes\\
\midrule
100-Year Flood Zone & \textcolor[HTML]{e76f52}{\textbf{-40}} & High & Expensive insurance, elevated construction\\
Significant Wetlands (>25\%) & \textcolor[HTML]{e76f52}{\textbf{-35}} & High & Federal/state permitting, mitigation required\\
Easements Present & \textcolor[HTML]{e76f52}{\textbf{-30}} & Moderate & May restrict building envelope\\
Historic District & \textcolor[HTML]{e76f52}{\textbf{-25}} & Moderate & Design review, material requirements\\
Moderate Wetlands (10-25\%) & \textcolor[HTML]{e76f52}{\textbf{-20}} & Low-Moderate & Potential buildable area reduction\\
\bottomrule
\end{longtabu}

}

\end{table}%

\begin{tcolorbox}[enhanced jigsaw, bottomtitle=1mm, title=\textcolor{quarto-callout-note-color}{\faInfo}\hspace{0.5em}{Assessment Framework}, colbacktitle=quarto-callout-note-color!10!white, titlerule=0mm, left=2mm, colframe=quarto-callout-note-color-frame, rightrule=.15mm, toptitle=1mm, breakable, leftrule=.75mm, arc=.35mm, coltitle=black, bottomrule=.15mm, toprule=.15mm, opacitybacktitle=0.6, opacityback=0, colback=white]

\textbf{Deal-Breakers} (Score: 0-30):

\begin{itemize}
\tightlist
\item
  Extensive wetlands covering majority of site
\item
  Active floodway designation
\item
  Conservation easements prohibiting development
\item
  Contaminated sites requiring remediation
\end{itemize}

\textbf{Speed-Bumps} (Score: 60-90):

\begin{itemize}
\tightlist
\item
  Partial flood zone (can design around)
\item
  Historic considerations (design flexibility)
\item
  Minor wetlands (avoidable)
\item
  Standard permitting requirements
\end{itemize}

\end{tcolorbox}

These constraints receive substantial score penalties because they
materially affect project feasibility and cost. Properties in 100-year
floodplains face expensive flood insurance, elevated construction costs,
and increasingly cautious lenders post-climate-change. Development in
such areas may be technically possible but financially marginal.

Significant wetlands (\textgreater25\% of parcel) trigger federal and
state permitting, potential mitigation requirements, and uncertainty
about buildable area. Easements---particularly those held by third
parties---can restrict development rights, limit building envelopes, or
prevent property subdivision.

Historic district designation doesn't prohibit development but adds
layers of design review, material requirements, and timeline
uncertainty. Some historic commissions embrace creative contemporary
additions; others mandate strict historicism that may conflict with
modern construction economics.

\section{Bringing It All Together}\label{bringing-it-all-together}

The final Development Potential Score is calculated as:

\[
\text{Score} = \sum_{i=1}^{6} (w_i \times s_i) - \text{Constraint Penalties}
\]

Where:

\begin{itemize}
\tightlist
\item
  \(w_i\) = weight of criterion \(i\)
\item
  \(s_i\) = score for criterion \(i\) (0-100)
\end{itemize}

\begin{figure}[H]

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{development-criteria_files/figure-pdf/fig-score-components-1.pdf}}

}

\caption{\label{fig-score-components}Development Score Component
Weights}

\end{figure}%

\textbf{Score Interpretation}:

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.4062}}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.1875}}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.4062}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Score Range
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Tier
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Description
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
75-100 & Tier 1 & \textbf{High Priority} - Immediate development
candidates \\
60-74 & Tier 2 & \textbf{Strong Potential} - Near-term opportunities \\
45-59 & Tier 3 & \textbf{Moderate Potential} - Requires creative
solutions \\
30-44 & Tier 4 & \textbf{Limited Potential} - Significant barriers
exist \\
\textless30 & Tier 5 & \textbf{Not Recommended} - Unsuitable for
development \\
\end{longtable}

These six criteria, combined with constraint penalties, create a
holistic picture of development potential. A property might score
exceptionally well on size and location but face significant challenges
from environmental constraints. Another might have modest physical
attributes but represent an urgent opportunity to support a financially
stressed congregation.

The weighted scoring system allows us to compare apples to oranges---to
evaluate whether a small, perfectly-located property in a historic
district outweighs a larger, unrestricted site with less market demand.
This methodology doesn't make decisions for stakeholders but rather
creates a common language for discussing trade-offs and priorities.

Ultimately, successful church real estate development requires more than
high scores. It demands patient capital, mission-aligned partners,
engaged congregations, and creative design. But by systematically
evaluating these criteria, we can identify the properties where stars
align---where market demand, congregational need, and regulatory
environment converge to create genuine opportunity.

\part{Analysis Results}

\chapter{Development Opportunity
Landscape}\label{development-opportunity-landscape}

\pandocbounded{\includegraphics[keepaspectratio]{development-landscape_files/figure-pdf/tier-distribution-visual-1.pdf}}

Nearly 1 in 5 properties (18) are high-potential candidates ready for
immediate developer outreach. Combined with 23 moderate-potential sites,
the Diocese has 41 actionable properties (41\%) forming a substantial
development pipeline to support long-term financial sustainability and
mission fulfillment. Properties classified as Constrained or Limited are
not necessarily without value---they may benefit from rezoning efforts,
environmental remediation, or alternative strategies such as land leases
or conservation easements.

\begin{tcolorbox}[enhanced jigsaw, bottomtitle=1mm, title=\textcolor{quarto-callout-note-color}{\faInfo}\hspace{0.5em}{Data Note}, colbacktitle=quarto-callout-note-color!10!white, titlerule=0mm, left=2mm, colframe=quarto-callout-note-color-frame, rightrule=.15mm, toptitle=1mm, breakable, leftrule=.75mm, arc=.35mm, coltitle=black, bottomrule=.15mm, toprule=.15mm, opacitybacktitle=0.6, opacityback=0, colback=white]

Of the \textbf{104} properties in the Diocese portfolio, \textbf{100}
are included in the development potential analysis. Four properties were
excluded as they fall below the minimum size threshold of 0.1 acres and
are not viable for independent development:

\begin{longtable*}[t]{lllrr}
\toprule
Property & Congregation & County & Acres & Sq Feet\\
\midrule
St Johns Episcopal Church & St Johns Episcopal Church & KING-WILLIAM & 0.066 & 2,871\\
St Johns Episcopal Church & St Johns Episcopal Church & KING-WILLIAM & 0.068 & 2,955\\
St Pauls Church & St Pauls Church & KING-WILLIAM & 0.027 & 1,185\\
St Johns Episcopal Church & St Johns Episcopal Church & KING-WILLIAM & 0.066 & 2,878\\
\bottomrule
\end{longtable*}

These parcels are likely slivers of land, parking strips, or cemetery
plots. While not candidates for independent development, they may hold
value as part of a larger assemblage or for their current use,
particularly for the St Johns Episcopal Church, which owns three of
these four parcels.

\end{tcolorbox}

\chapter{Geographic Distribution}\label{geographic-distribution-1}

\section{Interactive Map}\label{interactive-map}

Development opportunities are distributed broadly across the Diocese,
with the color gradient revealing where the highest-scoring properties
cluster. \textbf{High-potential properties (scores 60--80)}, shown in
deep red, are concentrated in the \textbf{Northern Virginia/DC corridor}
near Alexandria and Reston, as well as scattered throughout the
\textbf{Shenandoah Valley} from Winchester through Harrisonburg. These
sites score well due to favorable zoning, strong market conditions, and
fewer environmental constraints.

The \textbf{Fredericksburg region} stands out for its large-acreage
properties---represented by the largest circles on the map---though
these score in the \textbf{moderate range (40--50)}. Their size
represents significant opportunity, but factors such as zoning or
environmental considerations may require additional due diligence before
development.

Other potential development opportunities are spread across the Diocese,
including areas near Charlottesville and Richmond. These sites may
benefit from rezoning efforts or phased development strategies.

This geographic diversity is an asset: the Diocese can pursue high-score
``quick wins'' in Northern Virginia while simultaneously advancing
larger but more complex opportunities in growth corridors like
Fredericksburg. The portfolio supports both near-term revenue generation
and long-term strategic development.

\emph{The interactive map is available in the HTML version of this
report.}

\part{Summary Statistics}

\chapter{Property Portfolio Overview}\label{property-portfolio-overview}

\section{Portfolio Summary}\label{portfolio-summary-1}

\begin{figure}

\begin{minipage}{0.25\linewidth}

\begin{tcolorbox}[enhanced jigsaw, breakable, leftrule=.75mm, left=2mm, arc=.35mm, toprule=.15mm, bottomrule=.15mm, colframe=quarto-callout-note-color-frame, rightrule=.15mm, opacityback=0, colback=white]

\vspace{-3mm}\textbf{104}\vspace{3mm}

Total Parcels

\end{tcolorbox}

\end{minipage}%
%
\begin{minipage}{0.25\linewidth}

\begin{tcolorbox}[enhanced jigsaw, breakable, leftrule=.75mm, left=2mm, arc=.35mm, toprule=.15mm, bottomrule=.15mm, colframe=quarto-callout-tip-color-frame, rightrule=.15mm, opacityback=0, colback=white]

\vspace{-3mm}\textbf{248}\vspace{3mm}

Total Acres

\end{tcolorbox}

\end{minipage}%
%
\begin{minipage}{0.25\linewidth}

\begin{tcolorbox}[enhanced jigsaw, breakable, leftrule=.75mm, left=2mm, arc=.35mm, toprule=.15mm, bottomrule=.15mm, colframe=quarto-callout-warning-color-frame, rightrule=.15mm, opacityback=0, colback=white]

\vspace{-3mm}\textbf{36.1}\vspace{3mm}

Avg Development Score

\end{tcolorbox}

\end{minipage}%
%
\begin{minipage}{0.25\linewidth}

\begin{tcolorbox}[enhanced jigsaw, breakable, leftrule=.75mm, left=2mm, arc=.35mm, toprule=.15mm, bottomrule=.15mm, colframe=quarto-callout-important-color-frame, rightrule=.15mm, opacityback=0, colback=white]

\vspace{-3mm}\textbf{18}\vspace{3mm}

High Potential Properties

\end{tcolorbox}

\end{minipage}%

\end{figure}%

\section{Property Use Types}\label{property-use-types}

\begin{figure}[H]

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{property-portfolio_files/figure-pdf/fig-use-types-1.pdf}}

}

\caption{\label{fig-use-types}Distribution of Properties by Primary Use}

\end{figure}%

\section{Development Score
Distribution}\label{development-score-distribution}

Another way of looking at the data shared in the executive summary, one
can see that the portfolio is largely balanced in terms of opportunity,
if leaning slightly more towards the constrained and limited side of
options.

\begin{figure}[H]

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{property-portfolio_files/figure-pdf/fig-score-distribution-1.pdf}}

}

\caption{\label{fig-score-distribution}Distribution of Development
Scores Across Portfolio}

\end{figure}%

\section{Property Size vs Development
Score}\label{property-size-vs-development-score}

\begin{figure}[H]

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{property-portfolio_files/figure-pdf/fig-size-vs-score-1.pdf}}

}

\caption{\label{fig-size-vs-score}Development Scores by Property Size
Category}

\end{figure}%

The most high and moderate-potential properties concentrate in the 1--5
acre ``sweet spot,'' while parcels under 1 acre face inherent
limitations and the largest sites show more constraints. This indicates
that mid-sized properties offer the clearest path to development,
although some larger parcels show strong opportunities in other metrics.

\section{Summary Metrics}\label{summary-metrics}

\subsection{By County}

\begin{longtable}[t]{lrrrr}

\caption{\label{tbl-by-county}Property Distribution by County}

\tabularnewline

\toprule
\cellcolor[HTML]{445ca9}{\textcolor{white}{\textbf{County}}} & \cellcolor[HTML]{445ca9}{\textcolor{white}{\textbf{Parcels}}} & \cellcolor[HTML]{445ca9}{\textcolor{white}{\textbf{Total Acres}}} & \cellcolor[HTML]{445ca9}{\textcolor{white}{\textbf{Avg Score}}} & \cellcolor[HTML]{445ca9}{\textcolor{white}{\textbf{\# High Potential}}}\\
\midrule
FAUQUIER & 7 & 21.8 & 66.4 & 5\\
FAIRFAX-CITY & 3 & 8.2 & 63.3 & 2\\
ALBEMARLE & 3 & 12.6 & 55.0 & 1\\
CULPEPER & 3 & 17.9 & 41.7 & 1\\
ESSEX & 2 & 4.6 & 62.5 & 1\\
\addlinespace
FAIRFAX & 3 & 11.7 & 55.0 & 1\\
FREDERICK & 2 & 4.9 & 52.5 & 1\\
GOOCHLAND & 1 & 9.5 & 85.0 & 1\\
KING-WILLIAM & 19 & 16.3 & 23.4 & 1\\
LOUDOUN & 2 & 3.2 & 52.5 & 1\\
\addlinespace
RICHMOND & 7 & 7.1 & 35.0 & 1\\
ROCKINGHAM & 3 & 9.5 & 48.3 & 1\\
WESTMORELAND & 7 & 6.5 & 29.3 & 1\\
ALEXANDRIA & 1 & 0.3 & 20.0 & 0\\
ARLINGTON & 1 & 0.3 & 20.0 & 0\\
\bottomrule

\end{longtable}

\subsection{By Use Type}

\begin{longtable}[t]{lrrr}

\caption{\label{tbl-by-use}Property Statistics by Use Type}

\tabularnewline

\toprule
\cellcolor[HTML]{8baeaa}{\textcolor{white}{\textbf{Use Type}}} & \cellcolor[HTML]{8baeaa}{\textcolor{white}{\textbf{Count}}} & \cellcolor[HTML]{8baeaa}{\textcolor{white}{\textbf{Avg Size (Acres)}}} & \cellcolor[HTML]{8baeaa}{\textcolor{white}{\textbf{Avg Dev Score}}}\\
\midrule
Church & 78 & 1.92 & 36.8\\
Open Space & 23 & 4.29 & 35.7\\
Cemetery & 20 & 2.16 & 40.0\\
Residence & 12 & 0.66 & 21.7\\
Parking & 5 & 0.81 & 33.0\\
\bottomrule

\end{longtable}

\subsection{High Potential}

\begin{longtable}[t]{clllrrl}

\caption{\label{tbl-high-potential}Top 20 High Development Potential
Properties}

\tabularnewline

\toprule
\cellcolor[HTML]{445ca9}{\textcolor{white}{\textbf{Rank}}} & \cellcolor[HTML]{445ca9}{\textcolor{white}{\textbf{Address}}} & \cellcolor[HTML]{445ca9}{\textcolor{white}{\textbf{City}}} & \cellcolor[HTML]{445ca9}{\textcolor{white}{\textbf{County}}} & \cellcolor[HTML]{445ca9}{\textcolor{white}{\textbf{Acres}}} & \cellcolor[HTML]{445ca9}{\textcolor{white}{\textbf{Score}}} & \cellcolor[HTML]{445ca9}{\textcolor{white}{\textbf{Tier}}}\\
\midrule
\textbf{1} & \textbf{7420 MISSION HOME RD, FREE UNION 22940} & \textbf{FREE UNION} & \textbf{ALBEMARLE} & \textbf{3.12} & \textbf{85} & \textbf{High}\\
\textbf{2} & \textbf{16471 OAK SHADE RD, RIXEYVILLE 22737} & \textbf{RIXEYVILLE} & \textbf{CULPEPER} & \textbf{16.13} & \textbf{85} & \textbf{High}\\
\textbf{3} & \textbf{3663 TIDEWATER TRL, LORETTO 22509} & \textbf{LORETTO} & \textbf{ESSEX} & \textbf{2.08} & \textbf{85} & \textbf{High}\\
\textbf{4} & \textbf{10520 MAIN ST, FAIRFAX 22030} & \textbf{FAIRFAX} & \textbf{FAIRFAX-CITY} & \textbf{4.11} & \textbf{85} & \textbf{High}\\
\textbf{5} & \textbf{1 TRURO LN, FAIRFAX 22030} & \textbf{FAIRFAX} & \textbf{FAIRFAX-CITY} & \textbf{3.44} & \textbf{85} & \textbf{High}\\
\addlinespace
6 & 3241 BRUSH DR, FALLS CHURCH 22042 & FALLS CHURCH & FAIRFAX & 5.64 & 85 & High\\
7 & 5096 GRACE CHURCH LN, MIDLAND 22728 & MIDLAND & FAUQUIER & 3.65 & 85 & High\\
8 & 5092 GRACE CHURCH LN, MIDLAND 22728 & MIDLAND & FAUQUIER & 8.34 & 85 & High\\
9 & 5094 GRACE CHURCH LN, MIDLAND 22728 & MIDLAND & FAUQUIER & 2.76 & 85 & High\\
10 & 8695 OLD DUMFRIES RD, CATLETT 20119 & CATLETT & FAUQUIER & 2.36 & 85 & High\\
\addlinespace
11 & 403 NORTH RAPPAHANNOCK ST, REMINGTON 22734 & REMINGTON & FAUQUIER & 2.73 & 85 & High\\
12 & 1527 SENSENY RD, WINCHESTER 22602 & WINCHESTER & FREDERICK & 3.20 & 85 & High\\
13 & 1484 HOCKETT RD, MANAKIN SABOT 23103 & MANAKIN SABOT & GOOCHLAND & 9.49 & 85 & High\\
14 & 37018 GLENDALE ST, PURCELLVILLE 20132 & PURCELLVILLE & LOUDOUN & 2.02 & 85 & High\\
15 & FARNHAM 22460 & FARNHAM & RICHMOND & 2.05 & 85 & High\\
\addlinespace
16 & 7078 ROCKY BAR RD, ELKTON 22827 & ELKTON & ROCKINGHAM & 6.31 & 85 & High\\
17 & 103 SAINT JOHNS CHURCH LN, WEST POINT 23181 & WEST POINT & KING-WILLIAM & 12.51 & 85 & High\\
18 & WARSAW 22572 & WARSAW & WESTMORELAND & 2.72 & 85 & High\\
19 & 823 WATER ST, PORT ROYAL 22535 & PORT ROYAL & CAROLINE & 0.57 & 20 & Moderate\\
20 & DORSEY LANE LN, BOWLING GREEN 22427 & BOWLING GREEN & CAROLINE & 0.52 & 20 & Moderate\\
\bottomrule

\end{longtable}

\subsection{Development Tiers}

\begin{longtable}[t]{lrrrrr}

\caption{\label{tbl-tiers}Summary by Development Tier}

\tabularnewline

\toprule
\cellcolor[HTML]{e9ab3f}{\textcolor{white}{\textbf{Development Tier}}} & \cellcolor[HTML]{e9ab3f}{\textcolor{white}{\textbf{\# Parcels}}} & \cellcolor[HTML]{e9ab3f}{\textcolor{white}{\textbf{Total Acres}}} & \cellcolor[HTML]{e9ab3f}{\textcolor{white}{\textbf{Avg Acres}}} & \cellcolor[HTML]{e9ab3f}{\textcolor{white}{\textbf{Avg Score}}} & \cellcolor[HTML]{e9ab3f}{\textcolor{white}{\textbf{Avg Walkability}}}\\
\midrule
High & 18 & 92.7 & 5.15 & 85 & 6.8\\
Constrained & 25 & 123.3 & 4.93 & 40 & 5.7\\
Limited & 38 & 9.3 & 0.25 & 20 & 8.7\\
Moderate & 23 & 22.5 & 0.98 & 20 & 6.4\\
\bottomrule

\end{longtable}

\section{Congregation Health
Indicators}\label{congregation-health-indicators}

\begin{figure}[H]

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{property-portfolio_files/figure-pdf/fig-attendance-pledge-1.pdf}}

}

\caption{\label{fig-attendance-pledge}Congregation Health and Financial
Need}

\end{figure}%

\#\textbar{} echo: false \#\textbar{} results: asis

cat(``::: \{.callout-note\}\n'') cat(``\#\# Understanding Financial
Need\n'') cat(``Financial need reflects \textbf{trajectory, not current
resources}. Congregations flagged as `Financial Need' may still report
substantial annual giving, but their attendance and/or pledge revenue
have declined significantly since 2014. These congregations are not in
crisis today---but without intervention, they face an unsustainable
path. Development partnerships offer an opportunity to stabilize
finances while congregations remain viable, rather than waiting until
resources are exhausted.\n'') cat(``:::\n'')

\begin{longtable*}[t]{lrrrr}
\toprule
\cellcolor[HTML]{445ca9}{\textcolor{white}{\textbf{Congregation}}} & \cellcolor[HTML]{445ca9}{\textcolor{white}{\textbf{Avg Attendance}}} & \cellcolor[HTML]{445ca9}{\textcolor{white}{\textbf{Avg Pledge}}} & \cellcolor[HTML]{445ca9}{\textcolor{white}{\textbf{Attendance Change}}} & \cellcolor[HTML]{445ca9}{\textcolor{white}{\textbf{Pledge Change}}}\\
\midrule
Church of Our Redeemer & 19 & \$53,675 & -78.9\% & -68.3\%\\
Emmanuel Church & 25 & \$74,169 & -57.6\% & -43.2\%\\
St Johns Episcopal Church & 21 & \$96,947 & -55.3\% & -26.8\%\\
Grace Church Emmanuel Parish & 14 & \$72,564 & -51.7\% & -18.1\%\\
Piedmont/Bromfield Parish & 29 & \$70,810 & -51.7\% & -25.8\%\\
\addlinespace
St Stephens Church & 23 & \$101,136 & -50\% & -28.9\%\\
St James Church & 25 & \$55,882 & -21.9\% & -4.6\%\\
\bottomrule
\end{longtable*}

These congregations show the largest declines in attendance and pledge
over recent years.

\chapter{Geographic Distribution}\label{geographic-distribution-2}

\subsection{Parcels by Diocesan
Region}\label{parcels-by-diocesan-region}

\begin{longtable*}[t]{lrrrr}
\toprule
\cellcolor[HTML]{8baeaa}{\textcolor{white}{\textbf{County}}} & \cellcolor[HTML]{8baeaa}{\textcolor{white}{\textbf{\# Parcels}}} & \cellcolor[HTML]{8baeaa}{\textcolor{white}{\textbf{Total Acres}}} & \cellcolor[HTML]{8baeaa}{\textcolor{white}{\textbf{\% of Total Acreage}}} & \cellcolor[HTML]{8baeaa}{\textcolor{white}{\textbf{Avg Dev Score}}}\\
\midrule
KING-WILLIAM & 15 & 16 & 6.5 & 39.0\\
STAFFORD & 8 & 15 & 6.0 & 38.8\\
FAUQUIER & 7 & 22 & 8.8 & 80.7\\
FLUVANNA & 7 & 8 & 3.4 & 41.4\\
RICHMOND & 7 & 7 & 2.9 & 52.1\\
\addlinespace
WESTMORELAND & 7 & 7 & 2.6 & 55.0\\
CAROLINE & 5 & 2 & 0.8 & 48.0\\
CLARKE & 5 & 3 & 1.0 & 40.0\\
KING-GEORGE & 5 & 77 & 31.2 & 44.0\\
ALBEMARLE & 3 & 13 & 5.1 & 55.0\\
\addlinespace
CULPEPER & 3 & 18 & 7.2 & 75.0\\
FAIRFAX & 3 & 12 & 4.7 & 55.0\\
FAIRFAX-CITY & 3 & 8 & 3.3 & 80.0\\
ROCKINGHAM & 3 & 9 & 3.8 & 51.7\\
SHENANDOAH & 3 & 2 & 0.7 & 43.3\\
\addlinespace
ESSEX & 2 & 5 & 1.9 & 62.5\\
FREDERICK & 2 & 5 & 2.0 & 77.5\\
LOUDOUN & 2 & 3 & 1.3 & 77.5\\
MADISON & 2 & 1 & 0.4 & 30.0\\
PAGE & 2 & 2 & 0.9 & 55.0\\
\addlinespace
RICHMOND-CITY & 2 & 2 & 0.8 & 50.0\\
ALEXANDRIA & 1 & 0 & 0.1 & 30.0\\
ARLINGTON & 1 & 0 & 0.1 & 30.0\\
GOOCHLAND & 1 & 9 & 3.8 & 85.0\\
HANOVER & 1 & 1 & 0.6 & 70.0\\
\bottomrule
\end{longtable*}

Each of these counties have multiple congregation parcels, with the
highest concentration of small congregation parcels in King William and
Stafford counties.

\chapter{Congregation Vitality
Metrics}\label{congregation-vitality-metrics}

\textbf{Key Congregation Metrics:}

\begin{itemize}
\item
  \textbf{Congregations with \textless30 Sunday attendance:} 37
  (comprising 104 parcels across all congregations analyzed)
\item
  \textbf{Average parcels per congregation:} 2.8
\item
  \textbf{Average Sunday attendance:} 17 people
\item
  \textbf{Average annual pledge:} \$44,271
\item
  \textbf{Congregations with declining pledges:} 21
\item
  \textbf{Congregations in financial need (declining attendance +
  pledges):} 19
\end{itemize}

\chapter{Developable Land Summary}\label{developable-land-summary}

\subsection{Comprehensive Developability
Analysis}\label{comprehensive-developability-analysis}

\textbf{All Developable Properties (Score ≥45)}

\begin{figure}

\begin{minipage}{0.25\linewidth}

18

Developable Parcels

\end{minipage}%
%
\begin{minipage}{0.25\linewidth}

92.7

Developable Acres

\end{minipage}%
%
\begin{minipage}{0.25\linewidth}

\$10.1M

Assessed Value

\end{minipage}%
%
\begin{minipage}{0.25\linewidth}

1

With \textless30 Attendance

\end{minipage}%

\end{figure}%

\bookmarksetup{startatroot}

\chapter{Property Profiles}\label{property-profiles}

\section{Overvie}\label{overvie}

In this analysis, the top 10 properties all scored the same, which means
they are listed in no particular order, but as the top group of
high-possibility sites.

The following section provides detailed profiles for each of the top 10
development opportunities. Each profile includes:

\begin{itemize}
\tightlist
\item
  Site characteristics and current use
\item
  Congregation context (where applicable)
\item
  Development opportunities and strategies
\item
  Key considerations and next steps
\end{itemize}

\section*{Property \#1}\label{property-1}
\addcontentsline{toc}{section}{Property \#1}

\markright{Property \#1}

\subsection{10520 MAIN ST, FAIRFAX 22030}\label{main-st-fairfax-22030}

\textbf{FAIRFAX, FAIRFAX-CITY County}

\begin{tcolorbox}[enhanced jigsaw, bottomtitle=1mm, title=\textcolor{quarto-callout-important-color}{\faExclamation}\hspace{0.5em}{Development Score: \textbf{85/100}}, colbacktitle=quarto-callout-important-color!10!white, titlerule=0mm, left=2mm, colframe=quarto-callout-important-color-frame, rightrule=.15mm, toptitle=1mm, breakable, leftrule=.75mm, arc=.35mm, coltitle=black, bottomrule=.15mm, toprule=.15mm, opacitybacktitle=0.6, opacityback=0, colback=white]

\textbf{High}

\end{tcolorbox}

\begin{figure}

\begin{minipage}{0.33\linewidth}
\textbf{4.11 acres}\\
Property Size\end{minipage}%
%
\begin{minipage}{0.33\linewidth}
\textbf{16.3/20}\\
Walkability\end{minipage}%
%
\begin{minipage}{0.33\linewidth}
\textbf{25 people}\\
Avg Attendance\end{minipage}%

\end{figure}%

\subsubsection{Site Characteristics}\label{site-characteristics}

\begin{itemize}
\tightlist
\item
  \textbf{Current Uses:} Church building
\end{itemize}

\subsubsection{Congregation: Holy Cross Korean Episcopal
Church}\label{congregation-holy-cross-korean-episcopal-church}

\textbf{Financial Trend:} Plate \& pledge has ↑ increased by
\textbf{42\%} over the past decade.

\subsubsection{Development
Opportunities}\label{development-opportunities}

📐 \textbf{Substantial site:} Large parcel enables phased development or
creative master planning

🚶 \textbf{Highly walkable location:} Supports car-light households and
may qualify for reduced parking requirements

\subsubsection{Recommended Next Steps}\label{recommended-next-steps}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Site feasibility study and geotechnical analysis
\item
  Congregation leadership engagement
\item
  Zoning review and density bonus evaluation
\end{enumerate}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\section*{Property \#2}\label{property-2}
\addcontentsline{toc}{section}{Property \#2}

\markright{Property \#2}

\subsection{1 TRURO LN, FAIRFAX 22030}\label{truro-ln-fairfax-22030}

\textbf{FAIRFAX, FAIRFAX-CITY County}

\begin{tcolorbox}[enhanced jigsaw, bottomtitle=1mm, title=\textcolor{quarto-callout-important-color}{\faExclamation}\hspace{0.5em}{Development Score: \textbf{85/100}}, colbacktitle=quarto-callout-important-color!10!white, titlerule=0mm, left=2mm, colframe=quarto-callout-important-color-frame, rightrule=.15mm, toptitle=1mm, breakable, leftrule=.75mm, arc=.35mm, coltitle=black, bottomrule=.15mm, toprule=.15mm, opacitybacktitle=0.6, opacityback=0, colback=white]

\textbf{High}

\end{tcolorbox}

\begin{figure}

\begin{minipage}{0.33\linewidth}
\textbf{3.44 acres}\\
Property Size\end{minipage}%
%
\begin{minipage}{0.33\linewidth}
\textbf{16.3/20}\\
Walkability\end{minipage}%
%
\begin{minipage}{0.33\linewidth}
\textbf{25 people}\\
Avg Attendance\end{minipage}%

\end{figure}%

\subsubsection{Site Characteristics}\label{site-characteristics-1}

\begin{itemize}
\tightlist
\item
  \textbf{Current Uses:} Open space
\end{itemize}

\subsubsection{Congregation: Holy Cross Korean Episcopal
Church}\label{congregation-holy-cross-korean-episcopal-church-1}

\textbf{Financial Trend:} Plate \& pledge has ↑ increased by
\textbf{42\%} over the past decade.

\subsubsection{Development
Opportunities}\label{development-opportunities-1}

📐 \textbf{Substantial site:} Large parcel enables phased development or
creative master planning

🚶 \textbf{Highly walkable location:} Supports car-light households and
may qualify for reduced parking requirements

\subsubsection{Recommended Next Steps}\label{recommended-next-steps-1}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Site feasibility study and geotechnical analysis
\item
  Congregation leadership engagement
\item
  Zoning review and density bonus evaluation
\end{enumerate}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\section*{Property \#3}\label{property-3}
\addcontentsline{toc}{section}{Property \#3}

\markright{Property \#3}

\subsection{10490 MAIN ST, FAIRFAX 22030}\label{main-st-fairfax-22030-1}

\textbf{FAIRFAX, FAIRFAX-CITY County}

\begin{tcolorbox}[enhanced jigsaw, bottomtitle=1mm, title=\textcolor{quarto-callout-tip-color}{\faLightbulb}\hspace{0.5em}{Development Score: \textbf{70/100}}, colbacktitle=quarto-callout-tip-color!10!white, titlerule=0mm, left=2mm, colframe=quarto-callout-tip-color-frame, rightrule=.15mm, toptitle=1mm, breakable, leftrule=.75mm, arc=.35mm, coltitle=black, bottomrule=.15mm, toprule=.15mm, opacitybacktitle=0.6, opacityback=0, colback=white]

\textbf{Moderate}

\end{tcolorbox}

\begin{figure}

\begin{minipage}{0.33\linewidth}
\textbf{0.61 acres}\\
Property Size\end{minipage}%
%
\begin{minipage}{0.33\linewidth}
\textbf{16.3/20}\\
Walkability\end{minipage}%
%
\begin{minipage}{0.33\linewidth}
\textbf{25 people}\\
Avg Attendance\end{minipage}%

\end{figure}%

\subsubsection{Site Characteristics}\label{site-characteristics-2}

\begin{itemize}
\tightlist
\item
  \textbf{Current Uses:} Church building, Parking lot
\end{itemize}

\subsubsection{Congregation: Holy Cross Korean Episcopal
Church}\label{congregation-holy-cross-korean-episcopal-church-2}

\textbf{Financial Trend:} Plate \& pledge has ↑ increased by
\textbf{42\%} over the past decade.

\subsubsection{Development
Opportunities}\label{development-opportunities-2}

🅿️ \textbf{Prime opportunity:} Underutilized parking can support
structured parking with mixed-use above

🚶 \textbf{Highly walkable location:} Supports car-light households and
may qualify for reduced parking requirements

\subsubsection{Recommended Next Steps}\label{recommended-next-steps-2}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Site feasibility study and geotechnical analysis
\item
  Congregation leadership engagement
\item
  Zoning review and density bonus evaluation
\end{enumerate}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\section*{Property \#4}\label{property-4}
\addcontentsline{toc}{section}{Property \#4}

\markright{Property \#4}

\subsection{3241 BRUSH DR, FALLS CHURCH
22042}\label{brush-dr-falls-church-22042}

\textbf{FALLS CHURCH, FAIRFAX County}

\begin{tcolorbox}[enhanced jigsaw, bottomtitle=1mm, title=\textcolor{quarto-callout-important-color}{\faExclamation}\hspace{0.5em}{Development Score: \textbf{85/100}}, colbacktitle=quarto-callout-important-color!10!white, titlerule=0mm, left=2mm, colframe=quarto-callout-important-color-frame, rightrule=.15mm, toptitle=1mm, breakable, leftrule=.75mm, arc=.35mm, coltitle=black, bottomrule=.15mm, toprule=.15mm, opacitybacktitle=0.6, opacityback=0, colback=white]

\textbf{High}

\end{tcolorbox}

\begin{figure}

\begin{minipage}{0.33\linewidth}
\textbf{5.64 acres}\\
Property Size\end{minipage}%
%
\begin{minipage}{0.33\linewidth}
\textbf{13/20}\\
Walkability\end{minipage}%
%
\begin{minipage}{0.33\linewidth}
\textbf{21 people}\\
Avg Attendance\end{minipage}%

\end{figure}%

\subsubsection{Site Characteristics}\label{site-characteristics-3}

\begin{itemize}
\tightlist
\item
  \textbf{Current Uses:} Church building
\end{itemize}

\subsubsection{Congregation: St Patricks Anglo Vietnamese
Church}\label{congregation-st-patricks-anglo-vietnamese-church}

\textbf{Financial Trend:} Plate \& pledge has ↓ decreased by
\textbf{55.2\%} over the past decade.

\subsubsection{Development
Opportunities}\label{development-opportunities-3}

📐 \textbf{Substantial site:} Large parcel enables phased development or
creative master planning

🚶 \textbf{Moderate walkability:} Some transit access supports density
considerations

\subsubsection{Recommended Next Steps}\label{recommended-next-steps-3}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Site feasibility study and geotechnical analysis
\item
  Congregation leadership engagement
\item
  Zoning review and density bonus evaluation
\item
  Ground lease financial modeling
\end{enumerate}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\section*{Property \#5}\label{property-5}
\addcontentsline{toc}{section}{Property \#5}

\markright{Property \#5}

\subsection{11253 WEST RIVER RD, AYLETT
23009}\label{west-river-rd-aylett-23009}

\textbf{AYLETT, KING-WILLIAM County}

\begin{tcolorbox}[enhanced jigsaw, bottomtitle=1mm, title=\textcolor{quarto-callout-tip-color}{\faLightbulb}\hspace{0.5em}{Development Score: \textbf{70/100}}, colbacktitle=quarto-callout-tip-color!10!white, titlerule=0mm, left=2mm, colframe=quarto-callout-tip-color-frame, rightrule=.15mm, toptitle=1mm, breakable, leftrule=.75mm, arc=.35mm, coltitle=black, bottomrule=.15mm, toprule=.15mm, opacitybacktitle=0.6, opacityback=0, colback=white]

\textbf{Moderate}

\end{tcolorbox}

\begin{figure}

\begin{minipage}{0.33\linewidth}
\textbf{0.58 acres}\\
Property Size\end{minipage}%
%
\begin{minipage}{0.33\linewidth}
\textbf{4.8/20}\\
Walkability\end{minipage}%
%
\begin{minipage}{0.33\linewidth}
\textbf{11 people}\\
Avg Attendance\end{minipage}%

\end{figure}%

\subsubsection{Site Characteristics}\label{site-characteristics-4}

\begin{itemize}
\tightlist
\item
  \textbf{Current Uses:} Mixed use
\end{itemize}

\subsubsection{Congregation: St Davids
Church}\label{congregation-st-davids-church}

\textbf{Financial Trend:} Plate \& pledge has ↓ decreased by
\textbf{51.4\%} over the past decade.

\subsubsection{Development
Opportunities}\label{development-opportunities-4}

\subsubsection{Recommended Next Steps}\label{recommended-next-steps-4}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Site feasibility study and geotechnical analysis
\item
  Congregation leadership engagement
\item
  Zoning review and density bonus evaluation
\item
  Ground lease financial modeling
\end{enumerate}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\section*{Property \#6}\label{property-6}
\addcontentsline{toc}{section}{Property \#6}

\markright{Property \#6}

\subsection{37018 GLENDALE ST, PURCELLVILLE
20132}\label{glendale-st-purcellville-20132}

\textbf{PURCELLVILLE, LOUDOUN County}

\begin{tcolorbox}[enhanced jigsaw, bottomtitle=1mm, title=\textcolor{quarto-callout-important-color}{\faExclamation}\hspace{0.5em}{Development Score: \textbf{85/100}}, colbacktitle=quarto-callout-important-color!10!white, titlerule=0mm, left=2mm, colframe=quarto-callout-important-color-frame, rightrule=.15mm, toptitle=1mm, breakable, leftrule=.75mm, arc=.35mm, coltitle=black, bottomrule=.15mm, toprule=.15mm, opacitybacktitle=0.6, opacityback=0, colback=white]

\textbf{High}

\end{tcolorbox}

\begin{figure}

\begin{minipage}{0.33\linewidth}
\textbf{2.02 acres}\\
Property Size\end{minipage}%
%
\begin{minipage}{0.33\linewidth}
\textbf{8.5/20}\\
Walkability\end{minipage}%
%
\begin{minipage}{0.33\linewidth}
\textbf{0 people}\\
Avg Attendance\end{minipage}%

\end{figure}%

\subsubsection{Site Characteristics}\label{site-characteristics-5}

\begin{itemize}
\tightlist
\item
  \textbf{Current Uses:} Church building
\end{itemize}

\subsubsection{Congregation: St Peters
Church}\label{congregation-st-peters-church}

\textbf{Financial Trend:} Plate \& pledge has ↓ decreased by
\textbf{100\%} over the past decade.

\subsubsection{Development
Opportunities}\label{development-opportunities-5}

📐 \textbf{Substantial site:} Large parcel enables phased development or
creative master planning

\subsubsection{Recommended Next Steps}\label{recommended-next-steps-5}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Site feasibility study and geotechnical analysis
\item
  Congregation leadership engagement
\item
  Zoning review and density bonus evaluation
\item
  Ground lease financial modeling
\end{enumerate}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\section*{Property \#7}\label{property-7}
\addcontentsline{toc}{section}{Property \#7}

\markright{Property \#7}

\subsection{1484 HOCKETT RD, MANAKIN SABOT
23103}\label{hockett-rd-manakin-sabot-23103}

\textbf{MANAKIN SABOT, GOOCHLAND County}

\begin{tcolorbox}[enhanced jigsaw, bottomtitle=1mm, title=\textcolor{quarto-callout-important-color}{\faExclamation}\hspace{0.5em}{Development Score: \textbf{85/100}}, colbacktitle=quarto-callout-important-color!10!white, titlerule=0mm, left=2mm, colframe=quarto-callout-important-color-frame, rightrule=.15mm, toptitle=1mm, breakable, leftrule=.75mm, arc=.35mm, coltitle=black, bottomrule=.15mm, toprule=.15mm, opacitybacktitle=0.6, opacityback=0, colback=white]

\textbf{High}

\end{tcolorbox}

\begin{figure}

\begin{minipage}{0.33\linewidth}
\textbf{9.49 acres}\\
Property Size\end{minipage}%
%
\begin{minipage}{0.33\linewidth}
\textbf{3.5/20}\\
Walkability\end{minipage}%
%
\begin{minipage}{0.33\linewidth}
\textbf{20 people}\\
Avg Attendance\end{minipage}%

\end{figure}%

\subsubsection{Site Characteristics}\label{site-characteristics-6}

\begin{itemize}
\tightlist
\item
  \textbf{Current Uses:} Church building
\end{itemize}

\subsubsection{Congregation: St Francis Episcopal
Church}\label{congregation-st-francis-episcopal-church}

\textbf{Financial Trend:} Plate \& pledge has ↑ increased by
\textbf{7.9\%} over the past decade.

\subsubsection{Development
Opportunities}\label{development-opportunities-6}

📐 \textbf{Substantial site:} Large parcel enables phased development or
creative master planning

\subsubsection{Recommended Next Steps}\label{recommended-next-steps-6}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Site feasibility study and geotechnical analysis
\item
  Congregation leadership engagement
\item
  Zoning review and density bonus evaluation
\end{enumerate}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\section*{Property \#8}\label{property-8}
\addcontentsline{toc}{section}{Property \#8}

\markright{Property \#8}

\subsection{1704 WEST LABURNUM AVE, RICHMOND
23227}\label{west-laburnum-ave-richmond-23227}

\textbf{RICHMOND, RICHMOND-CITY County}

\begin{tcolorbox}[enhanced jigsaw, bottomtitle=1mm, title=\textcolor{quarto-callout-tip-color}{\faLightbulb}\hspace{0.5em}{Development Score: \textbf{70/100}}, colbacktitle=quarto-callout-tip-color!10!white, titlerule=0mm, left=2mm, colframe=quarto-callout-tip-color-frame, rightrule=.15mm, toptitle=1mm, breakable, leftrule=.75mm, arc=.35mm, coltitle=black, bottomrule=.15mm, toprule=.15mm, opacitybacktitle=0.6, opacityback=0, colback=white]

\textbf{Moderate}

\end{tcolorbox}

\begin{figure}

\begin{minipage}{0.33\linewidth}
\textbf{1.47 acres}\\
Property Size\end{minipage}%
%
\begin{minipage}{0.33\linewidth}
\textbf{12.3/20}\\
Walkability\end{minipage}%
%
\begin{minipage}{0.33\linewidth}
\textbf{18 people}\\
Avg Attendance\end{minipage}%

\end{figure}%

\subsubsection{Site Characteristics}\label{site-characteristics-7}

\begin{itemize}
\tightlist
\item
  \textbf{Current Uses:} Church building
\end{itemize}

\subsubsection{Congregation: Christ Ascension
Church}\label{congregation-christ-ascension-church}

\textbf{Financial Trend:} Plate \& pledge has ↓ decreased by
\textbf{69.4\%} over the past decade.

\subsubsection{Development
Opportunities}\label{development-opportunities-7}

📐 \textbf{Substantial site:} Large parcel enables phased development or
creative master planning

🚶 \textbf{Moderate walkability:} Some transit access supports density
considerations

\subsubsection{Recommended Next Steps}\label{recommended-next-steps-7}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Site feasibility study and geotechnical analysis
\item
  Congregation leadership engagement
\item
  Zoning review and density bonus evaluation
\item
  Ground lease financial modeling
\end{enumerate}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\section*{Property \#9}\label{property-9}
\addcontentsline{toc}{section}{Property \#9}

\markright{Property \#9}

\subsection{39518 LITTLE RIVER TPKE, ALDIE
20105}\label{little-river-tpke-aldie-20105}

\textbf{ALDIE, LOUDOUN County}

\begin{tcolorbox}[enhanced jigsaw, bottomtitle=1mm, title=\textcolor{quarto-callout-tip-color}{\faLightbulb}\hspace{0.5em}{Development Score: \textbf{70/100}}, colbacktitle=quarto-callout-tip-color!10!white, titlerule=0mm, left=2mm, colframe=quarto-callout-tip-color-frame, rightrule=.15mm, toptitle=1mm, breakable, leftrule=.75mm, arc=.35mm, coltitle=black, bottomrule=.15mm, toprule=.15mm, opacitybacktitle=0.6, opacityback=0, colback=white]

\textbf{Moderate}

\end{tcolorbox}

\begin{figure}

\begin{minipage}{0.33\linewidth}
\textbf{1.13 acres}\\
Property Size\end{minipage}%
%
\begin{minipage}{0.33\linewidth}
\textbf{7/20}\\
Walkability\end{minipage}%
%
\begin{minipage}{0.33\linewidth}
\textbf{19 people}\\
Avg Attendance\end{minipage}%

\end{figure}%

\subsubsection{Site Characteristics}\label{site-characteristics-8}

\begin{itemize}
\tightlist
\item
  \textbf{Current Uses:} Church building
\end{itemize}

\subsubsection{Congregation: Church of Our
Redeemer}\label{congregation-church-of-our-redeemer}

\textbf{Financial Trend:} Plate \& pledge has ↓ decreased by
\textbf{68.3\%} over the past decade.

\subsubsection{Development
Opportunities}\label{development-opportunities-8}

📐 \textbf{Substantial site:} Large parcel enables phased development or
creative master planning

\subsubsection{Recommended Next Steps}\label{recommended-next-steps-8}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Site feasibility study and geotechnical analysis
\item
  Congregation leadership engagement
\item
  Zoning review and density bonus evaluation
\item
  Ground lease financial modeling
\end{enumerate}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\section*{Property \#10}\label{property-10}
\addcontentsline{toc}{section}{Property \#10}

\markright{Property \#10}

\subsection{5092 GRACE CHURCH LN, MIDLAND
22728}\label{grace-church-ln-midland-22728}

\textbf{MIDLAND, FAUQUIER County}

\begin{tcolorbox}[enhanced jigsaw, bottomtitle=1mm, title=\textcolor{quarto-callout-important-color}{\faExclamation}\hspace{0.5em}{Development Score: \textbf{85/100}}, colbacktitle=quarto-callout-important-color!10!white, titlerule=0mm, left=2mm, colframe=quarto-callout-important-color-frame, rightrule=.15mm, toptitle=1mm, breakable, leftrule=.75mm, arc=.35mm, coltitle=black, bottomrule=.15mm, toprule=.15mm, opacitybacktitle=0.6, opacityback=0, colback=white]

\textbf{High}

\end{tcolorbox}

\begin{figure}

\begin{minipage}{0.33\linewidth}
\textbf{8.34 acres}\\
Property Size\end{minipage}%
%
\begin{minipage}{0.33\linewidth}
\textbf{5.7/20}\\
Walkability\end{minipage}%
%
\begin{minipage}{0.33\linewidth}
\textbf{14 people}\\
Avg Attendance\end{minipage}%

\end{figure}%

\subsubsection{Site Characteristics}\label{site-characteristics-9}

\begin{itemize}
\tightlist
\item
  \textbf{Current Uses:} Church building
\end{itemize}

\subsubsection{Congregation: Grace Church Emmanuel
Parish}\label{congregation-grace-church-emmanuel-parish}

\textbf{Financial Trend:} Plate \& pledge has ↓ decreased by
\textbf{18.1\%} over the past decade.

\subsubsection{Development
Opportunities}\label{development-opportunities-9}

📐 \textbf{Substantial site:} Large parcel enables phased development or
creative master planning

\subsubsection{Recommended Next Steps}\label{recommended-next-steps-9}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Site feasibility study and geotechnical analysis
\item
  Congregation leadership engagement
\item
  Zoning review and density bonus evaluation
\item
  Ground lease financial modeling
\end{enumerate}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\section{Interactive ADU Placement
Tool}\label{interactive-adu-placement-tool}

For an interactive experience, {[}\textbf{launch the ADU Placement
Dashboard}{]}

\part{Appendices}

\chapter*{Appendices}\label{appendices-1}
\addcontentsline{toc}{chapter}{Appendices}

\markboth{Appendices}{Appendices}

\begin{tcolorbox}[enhanced jigsaw, bottomtitle=1mm, title=\textcolor{quarto-callout-note-color}{\faInfo}\hspace{0.5em}{Technical Methodology}, colbacktitle=quarto-callout-note-color!10!white, titlerule=0mm, left=2mm, colframe=quarto-callout-note-color-frame, rightrule=.15mm, toptitle=1mm, breakable, leftrule=.75mm, arc=.35mm, coltitle=black, bottomrule=.15mm, toprule=.15mm, opacitybacktitle=0.6, opacityback=0, colback=white]

\textbf{Scoring Algorithm Details}

Each property receives scores across six dimensions (0-100 scale), which
are then weighted and combined:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \textbf{Size Score (20\% weight):} Properties between 0.5-5 acres
  score highest (100 points)
\item
  \textbf{Use Score (25\% weight):} Parking lots (95) and open space
  (90) score highest
\item
  \textbf{Location Score (20\% weight):} Based on walkability index and
  transit access
\item
  \textbf{Financial Score (15\% weight):} Congregation pledge trends
  indicate development need
\item
  \textbf{Market Score (10\% weight):} Area median income and LIHTC
  eligibility
\item
  \textbf{Zoning Score (10\% weight):} Development-friendly zoning
  receives 80 points
\end{enumerate}

\textbf{Constraint penalties} are applied after the weighted average,
with major penalties for: - Flood zones: -40 points - Significant
wetlands (\textgreater25\%): -35 points\\
- Easements: -30 points - Historic districts: -25 points

Final scores are capped between 0-100.

\end{tcolorbox}

\begin{tcolorbox}[enhanced jigsaw, bottomtitle=1mm, title=\textcolor{quarto-callout-note-color}{\faInfo}\hspace{0.5em}{Data Processing Notes}, colbacktitle=quarto-callout-note-color!10!white, titlerule=0mm, left=2mm, colframe=quarto-callout-note-color-frame, rightrule=.15mm, toptitle=1mm, breakable, leftrule=.75mm, arc=.35mm, coltitle=black, bottomrule=.15mm, toprule=.15mm, opacitybacktitle=0.6, opacityback=0, colback=white]

\textbf{Congregation-Parcel Joining:} Properties were matched to
congregation data using the \texttt{congr\_name} field. Properties
without matches received neutral financial scores.

\textbf{Missing Data Handling:} - Missing walkability scores defaulted
to 0 - Missing income data received median market scores (50) -
Properties without area or coordinates were excluded

\textbf{Quality Filters:} - Minimum parcel size: 0.1 acres - Required
valid lat/lon coordinates - Valid building years: 1700-2025

\end{tcolorbox}

\chapter{References}\label{references}




\end{document}
